# Generated by Django 4.1.7 on 2023-03-04 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sadio', '0002_library_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='creation_date',
        ),
    ]
